In [33]:
import pandas as pd
import numpy as np
import csv

# Chinese Sentences
---

In [10]:
col_names = ['c_id', 'lang','text']
cn_sentences = pd.read_csv('C:/Users/Alex/Desktop/CN-Sent.tsv', names = col_names, sep = '\t')
cn_sentences.head()

   c_id lang                    text
0     1  cmn                  我們試試看！
1     2  cmn                 我该去睡觉了。
2     3  cmn                 你在干什麼啊？
3     4  cmn                  這是什麼啊？
4     5  cmn  今天是６月１８号，也是Muiriel的生日！

# Chinese Audio
---

In [11]:
ad_col_names = ['c_id', 'username', 'license', 'att_url']
cn_audio = pd.read_csv('C:/Users/Alex/Desktop/CN-AdSent.csv', names = ad_col_names, sep = '\t')
cn_audio.head()

   c_id    username       license                                      att_url
0    61  fucongcong            \N                                           \N
1    68  fucongcong            \N                                           \N
2    78    mramosch            \N                                           \N
3    85      driini  CC BY-NC 4.0  https://tatoeba.org/deu/user/profile/driini
4    88      driini  CC BY-NC 4.0  https://tatoeba.org/deu/user/profile/driini

# Pinyin Transcripts
---

In [12]:
trans_col_names = ['c_id', 'lang', 'scrpt-nm', 'username', 'transcript']
cn_transcript = pd.read_csv('C:/Users/Alex/Desktop/CN-Transcripts.tsv', names = trans_col_names, sep = '\t')
cn_transcript.head()

,c_id,lang,scrpt-nm,username,transcript
0,4697666,cmn,Latn,adamtrousers,mei2you3ren2 zhi1dao4 wei4shen2me5 ta1 bu4 xi3...
1,4759996,cmn,Latn,ryanwoo,duan3yu3 shi4 ju4 fa3 dan1wei4 .
2,4760176,cmn,Latn,ryanwoo,ta1men5 hen3 kuai4 jiu4 liao2 qi3lai2 le5 .
3,4760180,cmn,Latn,ryanwoo,"bei4 ai4 bu4yi1 ding4 shi4 xing4fu2 , qu4 ai4 ..."
4,4760182,cmn,Latn,ryanwoo,"dao4 le5 duo1shao5 sui4 zhi1hou4 , wo3 cai2ne..."

# Sentence Links
---

In [13]:
# First column is the original sentence and the second column is the translation
links_col_names = ['c_id', 'e_id']
sentence_links = pd.read_csv('links.csv', names = links_col_names, sep = '\t')
sentence_links.head()

   c_id    e_id
0     1    1276
1     1    2481
2     1    5350
3     1    5972
4     1  180624

# English Sentences
---

In [14]:
en_col_names = ['e_id', 'lang','text']
en_sentences = pd.read_csv('EN-Sent.tsv', names = en_col_names, sep = '\t')
en_sentences.head()

   e_id lang                                              text
0  1276  eng                              Let's try something.
1  1277  eng                            I have to go to sleep.
2  1280  eng  Today is June 18th and it is Muiriel's birthday!
3  1282  eng                                Muiriel is 20 now.
4  1283  eng                        The password is "Muiriel".

# Merge Links and English Sentences
---

In [15]:
sentence_links.merge(en_sentences.drop(['lang'], axis = 1), on = 'e_id', how = 'inner').head()

   c_id  e_id                  text
0     1  1276  Let's try something.
1    77  1276  Let's try something.
2  2481  1276  Let's try something.
3  3091  1276  Let's try something.
4  4702  1276  Let's try something.

# Merge All
---

In [16]:
#cn_sentences.set_index('c_id').join(cn_audio.set_index('c_id'))
#cn_sentences.merge(cn_audio, on = 'c_id', how = 'inner')
#cn_sentences.merge(cn_audio.merge(cn_transcript[cn_transcript['scrpt-nm'] == 'Latn'], on = 'c_id', how = 'inner'), on = 'c_id', how = 'inner')

cn_sentences.drop(['lang'], axis=1).merge(
    cn_audio.drop(['username', 'license', 'att_url'], axis=1).merge(
        cn_transcript.drop(['lang', 'username'], axis=1)[cn_transcript['scrpt-nm']=='Latn'], on='c_id', how='inner'),
    on='c_id', how='inner').drop(['scrpt-nm'],axis=1)

,c_id,text,transcript
0,61,不要再把我当成“正常” 人!,"Bu4 yao4 zai4 ba3 wo3 dang4cheng2 ""zheng4chang..."
1,68,世界就是一个疯子的囚笼。,Shi4jie4 jiu4shi4 yi1 ge4 feng1zi5 de5 qiu2 lo...
2,332420,我收到了一张请帖。,Wo3 shou1dao4 le5 yi1 zhang1 qing3tie3.
3,332421,她半年后就要出国了。,Ta1 ban4 nian2 hou4 jiu4 yao4 chu1guo2 le5.
4,332422,很少人这么认为。,Hen3 shao3 ren2 zhe4me5 ren4wei2.
...,...,...,...
1673,8538013,耐心地坚持下去，有些事急不来。,"Nai4xin1 de5 jian1chi2 xia4qu4, you3xie1 shi4 ..."
1674,8603763,我父亲示意我离开会议室。,Wo3 fu4qin5 shi4yi4 wo3 li2kai1 hui4yi4shi4.
1675,8603786,一些植物无法适应寒冷。,Yi1xie1 zhi2wu4 wu2fa3 shi4ying4 han2leng3.
1676,8603787,自行车在汽车的右侧行驶是不合法的。,Zi4xing2che1 zai4 qi4che1 de5 you4 ce4 xing2sh...
1677,8796079,我们每天早上到公园里遛狗。,Wo3men5 mei3tian1 zao3shang5 dao4 gong1yuan2 l...

In [17]:
all_sent = cn_sentences.drop(['lang'], axis=1).merge(
    cn_audio.drop(['username', 'license', 'att_url'], axis=1).merge(
        cn_transcript.drop(['lang', 'username'], axis=1)[cn_transcript['scrpt-nm']=='Latn'].merge(
            sentence_links.merge(
                en_sentences.drop(['lang'], axis=1), 
                on='e_id', how='inner').drop(['e_id'], axis=1), 
            on='c_id', how='inner'), 
        on='c_id', how='inner'), 
    on='c_id', how='inner').drop(['scrpt-nm'],axis=1).drop_duplicates(subset=['c_id']).to_csv('all_sent.csv', sep='\t', index=False, header=False)

In [18]:
with open('all_sent.csv', 'r', encoding='utf-8-sig') as readFile:
    reader = csv.reader(readFile, delimiter='\t')
    lines  = list(reader)
    
tags = [lines[i][0] for i in range(len(lines))]

for i in range(len(lines)): lines[i].pop(0)

for i in range(len(lines)): lines[i].append(tags[i])
    
with open('all_sent.csv', 'w', encoding='utf-8-sig', newline='') as writeFile:
    writer = csv.writer(writeFile, delimiter='\t')
    writer.writerows(lines)

In [58]:
with open('all_sent.csv', 'r', encoding='utf-8-sig') as readFile:
    reader = csv.reader(readFile, delimiter='\t')
    lines  = list(reader)

In [3]:
cn_set = [lines[i][0] for i in range(len(lines))]

all_char = {}

for i in range(len(cn_set)):
    
    cn_set_spl = list(cn_set[i].replace(" ", "").replace(".", ""). replace("？", "").replace("！", "").replace("。", "").replace("一", "").replace("，", "").replace("…", ""))
    
    for j in range(len(cn_set_spl)):
        if cn_set_spl[j] in all_char:
            all_char[cn_set_spl[j]] = all_char[cn_set_spl[j]] + 1
        else:
            all_char[cn_set_spl[j]] = 1
            
sorted_char = sorted(all_char.items(), key = lambda x: x[1], reverse = True)
print('Character count:', len(sorted_char))
print('from', len(cn_set), "sentences")
print('-------------------')
#for i in range(len(sorted_char)): print(sorted_char[i][0], sorted_char[i][1])

Character count: 1531
from 1534 sentences
-------------------

In [21]:
with open('all_sent.csv', 'r', encoding = 'utf-8-sig', newline='') as readFile:
    reader = csv.reader(readFile, delimiter='\t')
    lines = list(reader)
    
cn_set = [lines[i][0] for i in range(len(lines))]

sent_level = np.zeros(len(lines))
hsk_chars = np.zeros(1)

for i in range(1, 7):
    
    if i == 1:
        with open('HSK1.txt', 'r', encoding = 'utf-8-sig') as readFile:
            reader = csv.reader(readFile)
            hsk_chars = list(reader)   
    else:
        with open(('HSK' + str(i) + '.txt'), 'r', encoding = 'utf-8-sig') as readFile:
            reader = csv.reader(readFile)
            hsk_chars = np.append(hsk_chars, list(reader))

for i in range(len(sent_level)):
    
    snt = cn_set[i]
    
    for j in range(len(snt)):
        if snt[j] in hsk_chars[0]:
            sent_level[i] = sent_level[i] + 1
        elif snt[j] in hsk_chars[1]:
            sent_level[i] = sent_level[i] + 2
        elif snt[j] in hsk_chars[2]:
            sent_level[i] = sent_level[i] + 3
        elif snt[j] in hsk_chars[3]:
            sent_level[i] = sent_level[i] + 4
        elif snt[j] in hsk_chars[4]:
            sent_level[i] = sent_level[i] + 5
        elif snt[j] in hsk_chars[5]:
            sent_level[i] = sent_level[i] + 6
        else:
            sent_level[i] = sent_level[i] + 0
            
    sent_level[i] = sent_level[i] / len(snt)
    
print(' -- sentence levels done -- ')

 -- sentence levels done --

In [22]:
for i in range(len(lines)): lines[i].append(sent_level[i])

In [23]:
with open('all_sent.csv', 'w', encoding='utf-8-sig', newline='') as writeFile:
    writer = csv.writer(writeFile, delimiter='\t')
    writer.writerows(lines)

In [27]:
lines.sort(key = lambda x : x[4])

[['Kate, 坐吧。', 'Kate,  zuo4 ba5.', 'Sit down, Kate.', '332793', '0.3333333333333333'], ['Steve看上去很高兴。', 'Steve kan4shang5qu5 hen3 gao1xing4.', 'Steve looks quite happy.', '333003', '0.5'], ['“是谁？”“是你妈妈。”', 'Shi4 shei2? "Shi4 ni3 ma1ma5."', 'Who is it? "It\'s your mother."', '334489', '0.5'], ['Ken的狗很大。', 'Ken de5 gou3 hen3 da4.', "Ken's dog is very big.", '334687', '0.5'], ['“你太好了。”Willie回答道。', 'Ni3 tai4 hao3 le5. Willie hui2da2 dao4.', "That's very nice of you, Willie answered.", '334473', '0.5294117647058824']]

In [28]:
with open('all_sent.csv', 'w', encoding='utf-8-sig', newline='') as writeFile:
    writer = csv.writer(writeFile, delimiter='\t')
    writer.writerows(lines)

In [62]:
def set_tone(letter, tone):
    
    if letter == 'a':
        if tone == 1:
            mod = 'a' + u'\u0304'
        elif tone == 2:
            mod = 'a' + u'\u0301'
        elif tone == 3:
            mod = 'a' + u'\u030C'
        elif tone == 4:
            mod = 'a' + u'\u0300'
        elif tone == 5:
            mod = 'a'
    elif letter == 'e':
        if tone == 1:
            mod = 'e' + u'\u0304'
        elif tone == 2:
            mod = 'e' + u'\u0301'
        elif tone == 3:
            mod = 'e' + u'\u030C'
        elif tone == 4:
            mod = 'e' + u'\u0300'
        elif tone == 5:
            mod = 'e'
    elif letter == 'i':
        if tone == 1:
            mod = 'i' + u'\u0304'
        elif tone == 2:
            mod = 'i' + u'\u0301'
        elif tone == 3:
            mod = 'i' + u'\u030C'
        elif tone == 4:
            mod = 'i' + u'\u0300'
        elif tone == 5:
            mod = 'i'
    elif letter == 'o':
        if tone == 1:
            mod = 'o' + u'\u0304'
        elif tone == 2:
            mod = 'o' + u'\u0301'
        elif tone == 3:
            mod = 'o' + u'\u030C'
        elif tone == 4:
            mod = 'o' + u'\u0300'
        elif tone == 5:
            mod = 'o'
    elif letter == 'u':
        if tone == 1:
            mod = 'u' + u'\u0304'
        elif tone == 2:
            mod = 'u' + u'\u0301'
        elif tone == 3:
            mod = 'u' + u'\u030C'
        elif tone == 4:
            mod = 'u' + u'\u0300'
        elif tone == 5:
            mod = 'u'
        
    return mod
        
        
def replace_at_index(orig_str, ind, replcmt):
    
    new_str = orig_str
    
    if ind < len(orig_str):
        new_str = orig_str[0:ind] + replcmt + orig_str[ind + 1:]
        
    return new_str


def get_letter(fragment, vowel_ind, vowels, tone):
    
    if 'a' in vowels:
        fragment = replace_at_index(fragment, vowel_ind[vowels.index('a')], set_tone('a', tone))
        
    elif 'e' in vowels:
        fragment = replace_at_index(fragment, vowel_ind[vowels.index('e')], set_tone('e', tone))
        
    elif ('o' in vowels) and ('e' in vowels):
        fragment = replace_at_index(fragment, vowel_ind[vowels.index('o')], set_tone('o', tone))
        
    else:
        fragment = replace_at_index(fragment, vowel_ind[-1], set_tone(vowels[-1], tone))
        
    return fragment


def start_mod(ex):
    num = ['1', '2', '3', '4', '5']
    vwl = ['a', 'e', 'i', 'o', 'u']
    spt = ex.split()
    for i in range(len(spt)):

        vowel_ind = []
        vowels = []
        tone = 0
        addit = 0

        j = 0

        while j < (len(spt[i])):

            if (spt[i][j] not in vwl) and (spt[i][j] not in num):
                if (j + 1) != len(spt[i]):
                    if (spt[i][j + 1] not in num):            
                        vowel_ind = []
                        vowels = []
                        tone = 0

            elif spt[i][j] in vwl:
                vowel_ind.append(j)
                vowels.append(spt[i][j])

            elif spt[i][j] in num:

                if len(vowel_ind) != 0:
                    tone = int(spt[i][j])
                    spt[i] = get_letter(spt[i], vowel_ind, vowels, tone)

                    vowel_ind = []
                    vowels = []
                    tone = 0

                    addit += 1

            j += 1

            if j == 100:
                break
                
    fnl = (' ').join(spt)
    return fnl

In [67]:
with open('all_sent.csv', 'r', encoding='utf-8-sig') as readFile:
    reader = csv.reader(readFile, delimiter='\t')
    lines  = list(reader)

In [ ]:
for l in range(len(lines)): lines[l][1] = start_mod(lines[l][1])

In [69]:
with open('all_sent.csv', 'w', encoding='utf-8-sig', newline='') as writeFile:
    writer = csv.writer(writeFile, delimiter='\t')
    writer.writerows(lines)